---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true



platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box

suites:
- name: default
  run_list:
  - recipe[citadel_test]
  attributes:
    citadel:
      bucket: citadel
      access_key_id: mykey
      secret_access_key: mysecret
