---
#<% IO.read('test/ec2/env').split.map{|s| s.split(/=/)}.each{|(k, v)| ENV[k] = v} if ::File.exist?('test/ec2/env') %>
#<% require 'poise_boiler' %>
<%= PoiseBoiler.kitchen(platforms: %w{ubuntu-14.04}, driver: 'ec2') %>

transport:
  name: sftp
  ssh_key: test/ec2/citadel-kitchen.key

suites:
- name: iam
  run_list:
  - recipe[citadel_test]
  driver:
    iam_profile_name: citadel-role
- name: attr
  run_list:
  - recipe[citadel_test]
  attributes:
    citadel:
      access_key_id: <%= ENV['CITADEL_ACCESS_KEY_ID'] %>
      secret_access_key: <%= ENV['CITADEL_SECRET_ACCESS_KEY'] %>
